version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./books:/app/books
      - ./faiss_index:/app/faiss_index
      - ./logs:/app/logs
      - ./ReadBooks:/app/ReadBooks
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_NAME}                # 创建用户 myuser
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: 